apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-origination-api.fullname" . }}
  labels:
    {{- include "account-origination-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "account-origination-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "account-origination-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "account-origination-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "account-origination-api.fullname" . }}
                  key: PORT
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "account-origination-api.fullname" . }}
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: x-api-key
                  value: {{ .Values.apiKeySecret.value | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: x-api-key
                  value: {{ .Values.apiKeySecret.value | quote }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
