name: API Quality Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  postman-api-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman
        run: postman login --with-api-key "${{ secrets.POSTMAN_API_KEY }}"

      - name: Lint OpenAPI spec
        run: postman spec lint "openapi.yaml" --report-events

      - name: Run Postman collection
        run: postman collection run 9474696-11099a3c-5db7-4d8f-a9b5-77397bb6c0f0 -e 9474696-9b8a9456-0370-4f2a-9f53-c12ac2fd7965 --report-events